spring.application:
    name: auth-service

server:
  port: ${AUTH_SERVICE_PORT:9002}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security.client: oauth2-local #could be oauth2-server, ldap, openid, kerberos etc.

users:
  provider: database

# HSQLDB DAO Configuration
spring:
  data:
    jpa:
      repositories:
        enabled: "true"
  jpa:
    hibernate:
      ddl-auto: "create"
      show_sql: true
      format_sql: true
    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.HSQLDialect}"
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.hsqldb.jdbc.JDBCDriver}"
    url: "${SPRING_DATASOURCE_URL:jdbc:hsqldb:file:${SQL_DATA_FOLDER:/tmp}/identity;sql.enforce_size=false}"
    username: "${SPRING_DATASOURCE_USERNAME:sa}"
    password: "${SPRING_DATASOURCE_PASSWORD:}"

