spring.application:
    name: auth-service

server:
  port: ${AUTH_SERVICE_PORT:9002}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security.client: oauth2-local #could be oauth2-server, ldap, openid, kerberos etc.
users:
  provider: database

