server:
  port: ${GATEWAY_PORT:8765}

spring:
  application:
    name: gateway-server

zuul:
  routes:
    functions:
      path: /functions/**
      sensitiveHeaders:
      serviceId: functions-service
    workflow:
      path: /workflows/**
      sensitiveHeaders:
      serviceId: workflow-service
    scheduler:
      path: /scheduler/**
      sensitiveHeaders:
      serviceId: scheduler
    idntity:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-service

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

proxy:
  auth:
    routes:
      functions: oauth2
      workflow: oauth2
      #identity: passthru