server:
  port: ${PORT:8765}

spring:
  application:
    name: gateway-server

zuul:
  routes:
    functions:
      path: /functions/**
      sensitiveHeaders:
      serviceId: functions-service
    workflow:
      path: /workflows/**
      sensitiveHeaders:
      serviceId: workflow-service

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/