server:
  port: ${GATEWAY_PORT:8765}

spring:
  application:
    name: gateway-server

zuul:
  routes:
    functions:
      path: /functions-api/**
      sensitiveHeaders:
      serviceId: functions-service
    workflow:
      path: /workflows-api/**
      sensitiveHeaders:
      serviceId: workflow-service
      #stripPrefix: true
    scheduler:
      path: /scheduler/**
      sensitiveHeaders:
      serviceId: scheduler
    idntity:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-service
    executor:
      path: /workflow-executor-api/**
      sensitiveHeaders:
      serviceId: workflow-executor

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#proxy:
#  auth:
#    routes:
#      functions: oauth2
#      workflow: oauth2
#      identity: passthru