server:
  port: ${PORT:9005}

spring:
  application:
    name: workflow-executor

spring.logging.file: ${LOG_FILE:${spring.application.name}/target}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

functions:
  source:
    template: "template.vm"
  ignite:
      config: "cache.xml"

spring:
  data:
    jpa:
      repositories:
        enabled: "true"
  jpa:
    hibernate:
      ddl-auto: "create"
      show_sql: true
      format_sql: true
    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.HSQLDialect}"
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.hsqldb.jdbc.JDBCDriver}"
    #change url accordingly
    url: "${SPRING_DATASOURCE_URL:jdbc:hsqldb:file:${SQL_DATA_FOLDER:/tmp}/functions;sql.enforce_size=false}"
    username: "${SPRING_DATASOURCE_USERNAME:sa}"
    password: "${SPRING_DATASOURCE_PASSWORD:}"