server:
  port: ${PORT:2222}

spring:
  application:
    name: functions-service

functions:
  input:
    location: "file:///home"
  output:
    location: "file:///home/functions"
  protocol: "file"
  ignite:
    config: "cache.xml"

  #Other options are s3, ftp, ftps, https etc

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/